### ISSUE TITLE
Extend the set of checked invalid characters to match that of s3inbox

### ISSUE THREAD

**Issue by MalinAhlberg** [NBISweden/sda-cli#330]
**Please describe the feature**
As a developer, I want the checks for invalid characters in sda-cli to be on par with those of s3inbox,  so that we double check and avoid any accidents with bad filenames in the future.

See relevant PR for the s3inbox can be found [here](https://github.com/neicnordic/sensitive-data-archive/pull/965).

**Acceptance criteria**
- [ ] 
- [ ] Tests verifying the changes are added

**Additional context**

**Estimation of size**: small
**Estimation of priority**: low/medium/high

**Comment by aaperis** [comment]
I believe there is no harm keeping the checks also in the sda-cli because this will have 2 benefits:
1. upload will not start from the user side if a file from the list of files has invalid characters so that we avoid a situation where some files are uploaded whereas some others aren't
2. in case a user uploads a large dataset with many files, the compute load will stay on the user side and s3inbox will be relieved from some resource consumption in handling files that it will eventually reject.

I don't see the checks in s3inbox as dublicate because they are either way needed if someone uses other tools to upload like s3cmd, or as a second check (given how much trouble we had when such filenames went through previously).

On the contrary, I suggest we expand the disallowed character list to match that of s3inbox as is done [here](https://github.com/neicnordic/sensitive-data-archive/pull/965).

**Comment by MalinAhlberg** [comment]
> I believe we should be keeping the checks in the sda-cli as well, because this will have 2 benefits:

Makes sense, good points. Is there anyway we could make sure that the list of disallowed characters is synced between the s3inbox and sda-cli? Might be overkill, but would be nice.

**Comment by aaperis** [comment]
> > I believe we should be keeping the checks in the sda-cli as well, because this will have 2 benefits:
> 
> Makes sense, good points. Is there anyway we could make sure that the list of disallowed characters is synced between the s3inbox and sda-cli? Might be overkill, but would be nice.

That would be nice, but seems like too much for what it is, hopefully after the addition of the current batch of disallowed characters we won't need to touch upon this in the future :-)
